branch-defaults:
  default:
    environment: udagram-api-env
environment-defaults:
  Udagram-api-env:
    branch: null
    repository: null
global:
  application_name: Udagram-Api
  default_ec2_keyname: null
  default_platform: Node.js 16 running on 64bit Amazon Linux 2
  default_region: me-south-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  sc: null
  workspace_type: Application
